### PR TITLE
DOC: small improvements to docs

### PR DESCRIPTION
**Pull request by theroggy**
- In python api docs of `exact_extract`:
    - Add link to "Available operations" to description of parameter `ops`.
    - Add link to the relevant section in the "Performance" to the description of parameter `strategy`.
- Clarify descriptions of operation arguments `default_value` and `default_weight`: reference https://github.com/isciences/exactextract/issues/147#issuecomment-2310699532
- In "index" page: change to exactextract being "accurate" description so it is applicable to more use cases.
- In "Installation" page, add conda as installation option.
- Set width : 100% on the table with all operations to rather have the description become multi-line on smaller screens than horizontal scrolbars appearing

### CODE REVIEW

**Comment by dbaston** [comment]
Thanks, these look like good changes to me. Do you intend to have it marked as "draft" ?

**Comment by theroggy** [comment]
> Thanks, these look like good changes to me. Do you intend to have it marked as "draft" ?

Yes, I'm still reading the docs, so might encounter other small things, and wasn't 100% sure about the syntacs for the link to "Avalable operations", so wanted to verify when built in this PR, but apparently the built version of the docs isn't available in the PR or do I miss something?

**Comment by dbaston** [comment]
Looks good now

image

**Comment by theroggy** [comment]
> Looks good now

Indeed, now the link works in both situations...

**Comment by dbaston** [comment]
Thanks for the careful review and corrections!

**Pull request merged**
